PERMISSIONS = [
    {'code': 'auth.login', 'grup': 'Genel', 'ad': 'Sisteme giriş', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'auth.logout', 'grup': 'Genel', 'ad': 'Oturum kapatma', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'main.portal', 'grup': 'Genel', 'ad': 'Portal ve kendi dashboard erişimi', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'main.profile_edit', 'grup': 'Genel', 'ad': 'Profil bilgilerini görüntüleme/düzenleme', 'tip': 'mudahale', 'all_active': True},
    {'code': 'main.search', 'grup': 'Genel', 'ad': 'Genel arama yapma', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'talep.create', 'grup': 'Talep', 'ad': 'Yeni satın alma talebi oluşturma', 'tip': 'mudahale', 'all_active': True},
    {'code': 'talep.own_view', 'grup': 'Talep', 'ad': 'Kendi taleplerini görüntüleme', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'talep.own_edit', 'grup': 'Talep', 'ad': 'Kendi bekleyen talebini düzenleme/silme', 'tip': 'mudahale', 'all_active': True},
    {'code': 'talep.pdf', 'grup': 'Talep', 'ad': 'Talep PDF çıktısı alma', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'talep.department_view', 'grup': 'Talep', 'ad': 'Departman taleplerini görüntüleme', 'tip': 'goruntuleme', 'roles': ('departman_yoneticisi',)},
    {'code': 'gm.dashboard', 'grup': 'Talep', 'ad': 'GM genel dashboard ve gecikmiş sipariş izleme', 'tip': 'goruntuleme', 'roles': ('gm',)},
    {'code': 'purchase.panel', 'grup': 'Satınalma', 'ad': 'Satınalma paneli ve raporları görüntüleme', 'tip': 'goruntuleme', 'roles': ('satinalma', 'admin', 'gm')},
    {'code': 'purchase.reports', 'grup': 'Satınalma', 'ad': 'Satınalma raporlarını görüntüleme', 'tip': 'goruntuleme', 'roles': ('satinalma', 'admin', 'gm')},
    {'code': 'purchase.price', 'grup': 'Satınalma', 'ad': 'Talep fiyatlandırma', 'tip': 'mudahale', 'roles': ('satinalma', 'admin')},
    {'code': 'purchase.item_edit', 'grup': 'Satınalma', 'ad': 'Talep kalemi düzenleme/çoğaltma/kopya silme', 'tip': 'mudahale', 'roles': ('satinalma', 'admin')},
    {'code': 'purchase.status', 'grup': 'Satınalma', 'ad': 'Talep durum değiştirme, onaylama, yolda, teslim, iptal', 'tip': 'mudahale', 'roles': ('satinalma', 'admin')},
    {'code': 'offer.view', 'grup': 'Satınalma', 'ad': 'Teklif listesi ve teklif detay görüntüleme', 'tip': 'goruntuleme', 'roles': ('satinalma', 'admin')},
    {'code': 'offer.manage', 'grup': 'Satınalma', 'ad': 'Teklif oluşturma, kalem ekleme/silme, teklif seçme', 'tip': 'mudahale', 'roles': ('satinalma', 'admin')},
    {'code': 'offer.reject_reason', 'grup': 'Satınalma', 'ad': 'Teklif kalemi red nedeni girme', 'tip': 'mudahale', 'roles': ('satinalma', 'admin')},
    {'code': 'offer.bulk', 'grup': 'Satınalma', 'ad': 'Toplu teklif oluşturma ve Excel çıktısı', 'tip': 'mudahale', 'roles': ('satinalma', 'admin')},
    {'code': 'offer.ai', 'grup': 'Satınalma', 'ad': 'Teklif mail okuma ve AI teklif analizi', 'tip': 'mudahale', 'roles': ('satinalma', 'admin')},
    {'code': 'po.output', 'grup': 'Satınalma', 'ad': 'PO PDF, PO Excel ve Outlook taslakları', 'tip': 'goruntuleme', 'roles': ('satinalma', 'admin')},
    {'code': 'po.mark_sent', 'grup': 'Satınalma', 'ad': 'PO gönderildi olarak işaretleme', 'tip': 'mudahale', 'roles': ('satinalma', 'admin')},
    {'code': 'purchase.order_report', 'grup': 'Satınalma', 'ad': 'Sipariş raporu ve sipariş özeti', 'tip': 'goruntuleme', 'roles': ('satinalma', 'admin')},
    {'code': 'supplier.manage', 'grup': 'Satınalma', 'ad': 'Tedarikçi yönetimi', 'tip': 'mudahale', 'roles': ('satinalma', 'admin')},
    {'code': 'supplier.import', 'grup': 'Satınalma', 'ad': 'Tedarikçi Excel yükleme ve şablon indirme', 'tip': 'mudahale', 'roles': ('satinalma', 'admin')},
    {'code': 'invoice.view', 'grup': 'Muhasebe', 'ad': 'Fatura ekranlarını görüntüleme', 'tip': 'goruntuleme', 'roles': ('muhasebe', 'satinalma', 'admin')},
    {'code': 'invoice.upload', 'grup': 'Muhasebe', 'ad': 'Fatura yükleme', 'tip': 'mudahale', 'roles': ('muhasebe', 'admin')},
    {'code': 'invoice.detail', 'grup': 'Muhasebe', 'ad': 'Fatura detay, PDF ve liste görüntüleme', 'tip': 'goruntuleme', 'roles': ('muhasebe', 'satinalma', 'admin')},
    {'code': 'invoice.match', 'grup': 'Muhasebe', 'ad': 'Fatura durum güncelleme ve siparişle eşleştirme', 'tip': 'mudahale', 'roles': ('muhasebe', 'satinalma', 'admin')},
    {'code': 'invoice.item_match', 'grup': 'Muhasebe', 'ad': 'Fatura manuel kalem eşleştirme', 'tip': 'mudahale', 'roles': ('muhasebe', 'satinalma', 'admin')},
    {'code': 'invoice.update', 'grup': 'Muhasebe', 'ad': 'Fatura güncelleme', 'tip': 'mudahale', 'roles': ('muhasebe', 'satinalma', 'admin')},
    {'code': 'invoice.delete', 'grup': 'Muhasebe', 'ad': 'Fatura silme', 'tip': 'mudahale', 'roles': ('muhasebe', 'satinalma', 'admin')},
    {'code': 'list.view', 'grup': 'Liste', 'ad': 'Malzeme ve ürün listelerini görüntüleme', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'list.manage', 'grup': 'Liste', 'ad': 'Malzeme ve ürün listelerini ekleme/düzenleme/silme', 'tip': 'mudahale', 'roles': ('admin',), 'special': 'liste_yetki'},
    {'code': 'list.material_autocomplete', 'grup': 'Liste', 'ad': 'Yeni talep ekranında malzeme autocomplete kullanma', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'list.material_ai', 'grup': 'Liste', 'ad': 'Yeni talep ekranında AI malzeme önerisi kullanma', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'list.product_auto', 'grup': 'Liste', 'ad': 'Yeni talep ekranında ürün autocomplete/otomatik ürün ekleme', 'tip': 'mudahale', 'all_active': True},
    {'code': 'list.purchase_history', 'grup': 'Liste', 'ad': 'Son alım ve kullanım sıklığı API bilgilerini görme', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'technical.view', 'grup': 'Teknik Resim', 'ad': 'Teknik resim kataloğunu görüntüleme', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'technical.folder_ajax', 'grup': 'Teknik Resim', 'ad': 'Teknik resim klasör içeriklerini AJAX ile görüntüleme', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'technical.download', 'grup': 'Teknik Resim', 'ad': 'Teknik resim görüntüleme/indirme', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'technical.manage', 'grup': 'Teknik Resim', 'ad': 'Teknik resim yükleme/silme', 'tip': 'mudahale', 'special': 'teknik_resim_yetki'},
    {'code': 'production.dashboard', 'grup': 'Üretim', 'ad': 'Üretim dashboard ve kayıt ekranları', 'tip': 'goruntuleme', 'roles': ('uretim', 'departman_yoneticisi', 'admin', 'gm')},
    {'code': 'production.entry', 'grup': 'Üretim', 'ad': 'Günlük üretim girişi', 'tip': 'mudahale', 'roles': ('uretim', 'departman_yoneticisi', 'admin', 'gm')},
    {'code': 'production.reports', 'grup': 'Üretim', 'ad': 'Üretim raporları', 'tip': 'goruntuleme', 'roles': ('uretim', 'departman_yoneticisi', 'admin', 'gm')},
    {'code': 'production.staff_view', 'grup': 'Üretim', 'ad': 'Üretim personel listesi ve performans detayları', 'tip': 'goruntuleme', 'roles': ('uretim', 'departman_yoneticisi', 'admin', 'gm')},
    {'code': 'production.staff_manage', 'grup': 'Üretim', 'ad': 'Üretim personeli ekleme/düzenleme/pasifleştirme', 'tip': 'mudahale', 'roles': ('uretim', 'departman_yoneticisi', 'admin', 'gm')},
    {'code': 'production.failure', 'grup': 'Üretim', 'ad': 'Üretim arıza kaydı oluşturma', 'tip': 'mudahale', 'roles': ('uretim', 'departman_yoneticisi', 'admin', 'gm')},
    {'code': 'production.station_manage', 'grup': 'Üretim', 'ad': 'İstasyon yönetimi', 'tip': 'mudahale', 'roles': ('departman_yoneticisi', 'admin')},
    {'code': 'planning.dashboard', 'grup': 'Planlama', 'ad': 'Planlama dashboard ve plan oluşturma', 'tip': 'goruntuleme', 'roles': ('planlama', 'departman_yoneticisi', 'admin')},
    {'code': 'planning.create', 'grup': 'Planlama', 'ad': 'Yeni haftalık plan oluşturma', 'tip': 'mudahale', 'roles': ('planlama', 'departman_yoneticisi', 'admin')},
    {'code': 'planning.list', 'grup': 'Planlama', 'ad': 'Plan listesi/geçmiş planlar', 'tip': 'goruntuleme', 'roles': ('planlama', 'departman_yoneticisi', 'admin')},
    {'code': 'planning.carryover', 'grup': 'Planlama', 'ad': 'Gün sonu devir işlemi', 'tip': 'mudahale', 'roles': ('planlama', 'departman_yoneticisi', 'admin', 'gm')},
    {'code': 'maintenance.dashboard', 'grup': 'Bakım', 'ad': 'Bakım dashboard görüntüleme', 'tip': 'goruntuleme', 'roles': ('bakim', 'departman_yoneticisi', 'admin')},
    {'code': 'maintenance.machine', 'grup': 'Bakım', 'ad': 'Makine listesi ve makine planları', 'tip': 'goruntuleme', 'roles': ('bakim', 'departman_yoneticisi', 'admin')},
    {'code': 'maintenance.record_plan', 'grup': 'Bakım', 'ad': 'Bakım kayıt ve bakım plan ekranları', 'tip': 'mudahale', 'roles': ('bakim', 'departman_yoneticisi', 'admin')},
    {'code': 'maintenance.calendar_report', 'grup': 'Bakım', 'ad': 'Bakım takvimi ve raporları', 'tip': 'goruntuleme', 'roles': ('bakim', 'departman_yoneticisi', 'admin')},
    {'code': 'maintenance.program', 'grup': 'Bakım', 'ad': 'Bakım programı oluşturma/güncelleme', 'tip': 'mudahale', 'roles': ('bakim', 'departman_yoneticisi', 'gm', 'admin')},
    {'code': 'maintenance.repair', 'grup': 'Bakım', 'ad': 'Arıza tamir kayıtları', 'tip': 'mudahale', 'roles': ('bakim', 'departman_yoneticisi', 'gm', 'admin')},
    {'code': 'maintenance.periodic', 'grup': 'Bakım', 'ad': 'Periyodik dış kontrol kayıtları', 'tip': 'mudahale', 'roles': ('bakim', 'departman_yoneticisi', 'gm', 'admin')},
    {'code': 'maintenance.api_check', 'grup': 'Bakım', 'ad': 'Üretim planı için bakım uyarısı API', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'quality.dashboard', 'grup': 'Kalite', 'ad': 'Kalite dashboard, DÖF, 8D ve süreç ekranları', 'tip': 'goruntuleme', 'roles': ('kalite', 'departman_yoneticisi', 'gm', 'admin')},
    {'code': 'quality.control_entry', 'grup': 'Kalite', 'ad': 'Kalite kontrol girişi', 'tip': 'mudahale', 'roles': ('kalite', 'admin')},
    {'code': 'quality.control_history', 'grup': 'Kalite', 'ad': 'Kalite kontrol geçmişi', 'tip': 'goruntuleme', 'roles': ('kalite', 'departman_yoneticisi', 'gm', 'admin')},
    {'code': 'quality.dof_view', 'grup': 'Kalite', 'ad': 'DÖF listesi, bana açılanlar, DÖF detay', 'tip': 'goruntuleme', 'roles': ('kalite', 'departman_yoneticisi', 'gm', 'admin')},
    {'code': 'quality.dof_create', 'grup': 'Kalite', 'ad': 'DÖF oluşturma', 'tip': 'mudahale', 'roles': ('kalite', 'admin')},
    {'code': 'quality.dof_manage', 'grup': 'Kalite', 'ad': 'DÖF aksiyon ekleme/tamamlama, ek yükleme, kapatma', 'tip': 'mudahale', 'roles': ('kalite', 'admin')},
    {'code': 'quality.dof_performance', 'grup': 'Kalite', 'ad': 'DÖF performans ekranı', 'tip': 'goruntuleme', 'roles': ('kalite', 'admin')},
    {'code': 'quality.8d_view', 'grup': 'Kalite', 'ad': '8D listesi ve detay görüntüleme', 'tip': 'goruntuleme', 'roles': ('kalite', 'departman_yoneticisi', 'gm', 'admin')},
    {'code': 'quality.8d_manage', 'grup': 'Kalite', 'ad': '8D oluşturma/düzenleme', 'tip': 'mudahale', 'roles': ('kalite', 'admin')},
    {'code': 'quality.8d_output', 'grup': 'Kalite', 'ad': '8D PDF, Excel ve Outlook çıktıları', 'tip': 'goruntuleme', 'roles': ('kalite', 'departman_yoneticisi', 'gm', 'admin')},
    {'code': 'quality.process_view', 'grup': 'Kalite', 'ad': 'Süreç listesi ve süreç görüntüleme', 'tip': 'goruntuleme', 'roles': ('kalite', 'departman_yoneticisi', 'gm', 'admin')},
    {'code': 'quality.process_manage', 'grup': 'Kalite', 'ad': 'Süreç oluşturma/düzenleme/durum/adım yönetimi', 'tip': 'mudahale', 'roles': ('kalite', 'admin')},
    {'code': 'quality.dof_api', 'grup': 'Kalite', 'ad': 'DÖF uyarı API', 'tip': 'goruntuleme', 'all_active': True},
    {'code': 'admin.users', 'grup': 'Admin', 'ad': 'Kullanıcı yönetimi', 'tip': 'goruntuleme', 'roles': ('admin',)},
    {'code': 'admin.permissions', 'grup': 'Admin', 'ad': 'Yetki matrisi görüntüleme/düzenleme', 'tip': 'mudahale', 'roles': ('admin',)},
    {'code': 'admin.user_manage', 'grup': 'Admin', 'ad': 'Kullanıcı ekleme/düzenleme/pasifleştirme/şifre sıfırlama', 'tip': 'mudahale', 'roles': ('admin',)},
    {'code': 'admin.server', 'grup': 'Admin', 'ad': 'Sunucu durumu ve restart ekranı', 'tip': 'mudahale', 'roles': ('admin',)},
    {'code': 'admin.server_metrics', 'grup': 'Admin', 'ad': 'Sunucu canlı CPU/RAM/disk verilerini görüntüleme', 'tip': 'goruntuleme', 'roles': ('admin',)},
]

PERMISSION_BY_CODE = {p['code']: p for p in PERMISSIONS}

ENDPOINT_PERMISSIONS = {
    'main.profil': 'main.profile_edit',
    'main.arama': 'main.search',
    'main.yeni_talep': 'talep.create',
    'main.talep_detay': 'talep.own_view',
    'main.talep_duzenle': 'talep.own_edit',
    'main.talep_sil': 'talep.own_edit',
    'main.talep_pdf': 'talep.pdf',
    'satin_alma.panel': 'purchase.panel',
    'satin_alma.raporlar': 'purchase.reports',
    'satin_alma.fiyatlandir': 'purchase.price',
    'satin_alma.kalem_duzenle': 'purchase.item_edit',
    'satin_alma.kalem_cogalt': 'purchase.item_edit',
    'satin_alma.kalem_kopya_sil': 'purchase.item_edit',
    'satin_alma.onayla': 'purchase.status',
    'satin_alma.iptal': 'purchase.status',
    'satin_alma.yolda': 'purchase.status',
    'satin_alma.teslim': 'purchase.status',
    'satin_alma.durum_guncelle': 'purchase.status',
    'satin_alma.teklif_listesi': 'offer.view',
    'satin_alma.teklif_detay': 'offer.view',
    'satin_alma.teklif_yeni': 'offer.manage',
    'satin_alma.teklif_kalem_ekle': 'offer.manage',
    'satin_alma.teklif_kalem_sil': 'offer.manage',
    'satin_alma.teklif_sec': 'offer.manage',
    'satin_alma.teklif_kalem_red_nedeni': 'offer.reject_reason',
    'satin_alma.teklif_toplu_yeni': 'offer.bulk',
    'satin_alma.teklif_toplu': 'offer.bulk',
    'satin_alma.teklif_toplu_ekle': 'offer.bulk',
    'satin_alma.teklif_toplu_excel': 'offer.bulk',
    'satin_alma.teklif_ai_yukle': 'offer.ai',
    'satin_alma.teklif_mail_oku': 'offer.ai',
    'satin_alma.teklif_ai_tavsiye': 'offer.ai',
    'satin_alma.teklif_po_pdf': 'po.output',
    'satin_alma.teklif_po_eml': 'po.output',
    'satin_alma.kalem_po_eml': 'po.output',
    'satin_alma.siparis_excel': 'po.output',
    'satin_alma.teklif_po_gonder': 'po.mark_sent',
    'satin_alma.siparis_ozet': 'purchase.order_report',
    'satin_alma.siparis_raporu': 'purchase.order_report',
    'admin.tedarikci_listesi': 'supplier.manage',
    'admin.tedarikci_ekle': 'supplier.manage',
    'admin.tedarikci_duzenle': 'supplier.manage',
    'admin.tedarikci_sil': 'supplier.manage',
    'admin.tedarikci_excel_yukle': 'supplier.import',
    'admin.tedarikci_sablon_indir': 'supplier.import',
    'muhasebe.fatura_listesi': 'invoice.view',
    'muhasebe.fatura_yukle': 'invoice.upload',
    'muhasebe.fatura_detay': 'invoice.detail',
    'muhasebe.fatura_pdf_indir': 'invoice.detail',
    'muhasebe.fatura_durum': 'invoice.match',
    'muhasebe.fatura_esles': 'invoice.match',
    'muhasebe.fatura_kalem_esles_manuel': 'invoice.item_match',
    'muhasebe.fatura_guncelle': 'invoice.update',
    'muhasebe.fatura_sil': 'invoice.delete',
    'admin.malzeme_listesi': 'list.view',
    'admin.urun_listesi': 'list.view',
    'admin.malzeme_ekle': 'list.manage',
    'admin.malzeme_duzenle': 'list.manage',
    'admin.malzeme_sil': 'list.manage',
    'admin.urun_ekle': 'list.manage',
    'admin.urun_duzenle': 'list.manage',
    'admin.urun_sil': 'list.manage',
    'api.malzeme_ara': 'list.material_autocomplete',
    'api.malzeme_oneri': 'list.material_ai',
    'api.urun_ara': 'list.product_auto',
    'api.urun_otomatik_ekle': 'list.product_auto',
    'main.son_alim_api': 'list.purchase_history',
    'main.kullanim_sikligi_api': 'list.purchase_history',
    'teknik_resim.teknik_resim_listesi': 'technical.view',
    'teknik_resim.klasor_icerik': 'technical.folder_ajax',
    'teknik_resim.teknik_resim_goruntule': 'technical.download',
    'teknik_resim.teknik_resim_indir': 'technical.download',
    'teknik_resim.teknik_resim_yukle': 'technical.manage',
    'teknik_resim.teknik_resim_sil': 'technical.manage',
    'uretim.uretim_dashboard': 'production.dashboard',
    'uretim.uretim_giris': 'production.entry',
    'uretim.uretim_raporlar': 'production.reports',
    'uretim.personel_listesi': 'production.staff_view',
    'uretim.personel_detay': 'production.staff_view',
    'uretim.personel_ekle': 'production.staff_manage',
    'uretim.personel_duzenle': 'production.staff_manage',
    'uretim.personel_pasif': 'production.staff_manage',
    'uretim.ariza_kaydi': 'production.failure',
    'uretim.istasyon_yonetim': 'production.station_manage',
    'planlama.planlama_dashboard': 'planning.dashboard',
    'planlama.yeni_plan': 'planning.create',
    'planlama.plan_listesi': 'planning.list',
    'planlama.gun_sonu_devir': 'planning.carryover',
    'bakim.bakim_dashboard': 'maintenance.dashboard',
    'bakim.makine_listesi': 'maintenance.machine',
    'bakim.makine_planlari': 'maintenance.machine',
    'bakim.bakim_kayit': 'maintenance.record_plan',
    'bakim.bakim_plan': 'maintenance.record_plan',
    'bakim.bakim_takvim': 'maintenance.calendar_report',
    'bakim.bakim_raporlar': 'maintenance.calendar_report',
    'bakim.bakim_program': 'maintenance.program',
    'bakim.program_durum': 'maintenance.program',
    'bakim.ariza_tamir_listesi': 'maintenance.repair',
    'bakim.periyodik_listesi': 'maintenance.periodic',
    'api.api_bakim_kontrol': 'maintenance.api_check',
    'kalite.kalite_dashboard': 'quality.dashboard',
    'kalite.kontrol_giris': 'quality.control_entry',
    'kalite.kontrol_gecmis': 'quality.control_history',
    'kalite.dof_listesi': 'quality.dof_view',
    'kalite.dof_benim': 'quality.dof_view',
    'kalite.dof_detay': 'quality.dof_view',
    'kalite.dof_yeni': 'quality.dof_create',
    'kalite.dof_aksiyon_ekle': 'quality.dof_manage',
    'kalite.aksiyon_tamamla': 'quality.dof_manage',
    'kalite.dof_ek_yukle': 'quality.dof_manage',
    'kalite.dof_kapat': 'quality.dof_manage',
    'kalite.dof_performans': 'quality.dof_performance',
    'kalite.sekizd_listesi': 'quality.8d_view',
    'kalite.sekizd_detay': 'quality.8d_view',
    'kalite.sekizd_yeni': 'quality.8d_manage',
    'kalite.sekizd_duzenle': 'quality.8d_manage',
    'kalite.sekizd_pdf': 'quality.8d_output',
    'kalite.sekizd_excel': 'quality.8d_output',
    'kalite.sekizd_eml': 'quality.8d_output',
    'kalite.surec_listesi': 'quality.process_view',
    'kalite.surec_goruntur': 'quality.process_view',
    'kalite.surec_yeni': 'quality.process_manage',
    'kalite.surec_duzenle': 'quality.process_manage',
    'kalite.adim_ekle': 'quality.process_manage',
    'kalite.adim_sil': 'quality.process_manage',
    'kalite.adim_sira_degistir': 'quality.process_manage',
    'kalite.surec_durum': 'quality.process_manage',
    'kalite.api_dof_uyarilar': 'quality.dof_api',
    'admin.kullanicilar': 'admin.users',
    'admin.yetki_matrisi': 'admin.permissions',
    'admin.yetki_matrisi_kaydet': 'admin.permissions',
    'admin.kullanici_ekle': 'admin.user_manage',
    'admin.kullanici_duzenle': 'admin.user_manage',
    'admin.kullanici_sil': 'admin.user_manage',
    'admin.kullanici_sifre_sifirla': 'admin.user_manage',
    'admin.sunucu_dashboard': 'admin.server',
    'admin.sunucu_restart': 'admin.server',
    'admin.sunucu_durum_api': 'admin.server_metrics',
}


def default_permission_allowed(user, permission):
    if not user or not getattr(user, 'is_active', False):
        return False
    if permission.get('all_active'):
        return True
    if user.role in permission.get('roles', ()):
        return True
    special = permission.get('special')
    if special and getattr(user, special, False):
        return True
    return False


def user_permission_overrides(user):
    return {p.permission_code: p.allowed for p in getattr(user, 'yetkiler', [])}


def has_permission(user, code):
    permission = PERMISSION_BY_CODE.get(code)
    if not permission:
        return False
    overrides = user_permission_overrides(user)
    if code in overrides:
        return bool(overrides[code])
    return default_permission_allowed(user, permission)
