"""b001_planli_bakim_periyodik_kontrol_makine_guncelleme

Revision ID: 657e2789fa39
Revises: 73f5a4c0eaac
Create Date: 2026-05-02 12:35:43.546226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657e2789fa39'
down_revision = '73f5a4c0eaac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakim_kaydi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baslangic_saati', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('bitis_saati', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('parca_kullanildi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('kullanilan_parcalar', sa.Text(), nullable=True))

    with op.batch_alter_table('makine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('islev', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('lokasyon', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('guc_kw', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('uretim_yili', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('istasyon_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_makine_istasyon', 'is_istasyonu', ['istasyon_id'], ['id'])

    # planli_bakim ve periyodik_kontrol tabloları db.create_all ile oluşturulacak
    # teklif_grubu FK zaten mevcut — skip

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('makine', schema=None) as batch_op:
        batch_op.drop_constraint('fk_makine_istasyon', type_='foreignkey')
        batch_op.drop_column('istasyon_id')
        batch_op.drop_column('uretim_yili')
        batch_op.drop_column('guc_kw')
        batch_op.drop_column('lokasyon')
        batch_op.drop_column('islev')

    with op.batch_alter_table('bakim_kaydi', schema=None) as batch_op:
        batch_op.drop_column('kullanilan_parcalar')
        batch_op.drop_column('parca_kullanildi')
        batch_op.drop_column('bitis_saati')
        batch_op.drop_column('baslangic_saati')

    # ### end Alembic commands ###
