"""P001 uretim personeli kalite dof 8d is akisi modelleri

Revision ID: 73f5a4c0eaac
Revises: 8d3f7a2c9b10
Create Date: 2026-05-02 07:29:09.959420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f5a4c0eaac'
down_revision = '8d3f7a2c9b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_fatura')
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fatura_durum'), ['durum'], unique=False)
        batch_op.create_index(batch_op.f('ix_fatura_fatura_no'), ['fatura_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_fatura_talep_id'), ['talep_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fatura_tedarikci_id'), ['tedarikci_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fatura_yukleme_tarihi'), ['yukleme_tarihi'], unique=False)
        batch_op.drop_column('iskonto_tutari')
        batch_op.drop_column('iskonto_orani')

    with op.batch_alter_table('fatura_kalem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fatura_kalem_fatura_id'), ['fatura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fatura_kalem_talep_kalem_id'), ['talep_kalem_id'], unique=False)

    with op.batch_alter_table('talep_formu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_talep_created_at'))
        batch_op.drop_index(batch_op.f('idx_talep_department_id'))
        batch_op.drop_index(batch_op.f('idx_talep_durum'))
        batch_op.drop_index(batch_op.f('idx_talep_durum_created'))
        batch_op.drop_index(batch_op.f('idx_talep_eden_id'))
        batch_op.create_index(batch_op.f('ix_talep_formu_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_talep_formu_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_talep_formu_durum'), ['durum'], unique=False)
        batch_op.create_index(batch_op.f('ix_talep_formu_siparis_no'), ['siparis_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_talep_formu_talep_eden_id'), ['talep_eden_id'], unique=False)

    with op.batch_alter_table('talep_kalem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_kalem_talep_id'))
        batch_op.drop_index(batch_op.f('idx_kalem_tedarikci_id'))
        batch_op.create_index(batch_op.f('ix_talep_kalem_malzeme_adi'), ['malzeme_adi'], unique=False)
        batch_op.create_index(batch_op.f('ix_talep_kalem_malzeme_turu'), ['malzeme_turu'], unique=False)
        batch_op.create_index(batch_op.f('ix_talep_kalem_talep_id'), ['talep_id'], unique=False)

    with op.batch_alter_table('tedarikci', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tedarikci_name'), ['name'], unique=False)

    # teklif_grubu FK already exists in DB — skipped

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_department_id'), ['department_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_department_id'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    # teklif_grubu FK drop skipped

    with op.batch_alter_table('tedarikci', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tedarikci_name'))

    with op.batch_alter_table('talep_kalem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_talep_kalem_talep_id'))
        batch_op.drop_index(batch_op.f('ix_talep_kalem_malzeme_turu'))
        batch_op.drop_index(batch_op.f('ix_talep_kalem_malzeme_adi'))
        batch_op.create_index(batch_op.f('idx_kalem_tedarikci_id'), ['tedarikci_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_kalem_talep_id'), ['talep_id'], unique=False)

    with op.batch_alter_table('talep_formu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_talep_formu_talep_eden_id'))
        batch_op.drop_index(batch_op.f('ix_talep_formu_siparis_no'))
        batch_op.drop_index(batch_op.f('ix_talep_formu_durum'))
        batch_op.drop_index(batch_op.f('ix_talep_formu_department_id'))
        batch_op.drop_index(batch_op.f('ix_talep_formu_created_at'))
        batch_op.create_index(batch_op.f('idx_talep_eden_id'), ['talep_eden_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_talep_durum_created'), ['durum', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_talep_durum'), ['durum'], unique=False)
        batch_op.create_index(batch_op.f('idx_talep_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_talep_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('fatura_kalem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fatura_kalem_talep_kalem_id'))
        batch_op.drop_index(batch_op.f('ix_fatura_kalem_fatura_id'))

    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iskonto_orani', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('iskonto_tutari', sa.FLOAT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_fatura_yukleme_tarihi'))
        batch_op.drop_index(batch_op.f('ix_fatura_tedarikci_id'))
        batch_op.drop_index(batch_op.f('ix_fatura_talep_id'))
        batch_op.drop_index(batch_op.f('ix_fatura_fatura_no'))
        batch_op.drop_index(batch_op.f('ix_fatura_durum'))

    op.create_table('_alembic_tmp_fatura',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fatura_no', sa.VARCHAR(length=100), nullable=True),
    sa.Column('fatura_tarihi', sa.DATE(), nullable=True),
    sa.Column('vade_tarihi', sa.DATE(), nullable=True),
    sa.Column('tedarikci_id', sa.INTEGER(), nullable=True),
    sa.Column('tedarikci_adi_ham', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ara_toplam', sa.FLOAT(), nullable=True),
    sa.Column('kdv_tutari', sa.FLOAT(), nullable=True),
    sa.Column('genel_toplam', sa.FLOAT(), nullable=True),
    sa.Column('para_birimi', sa.VARCHAR(length=10), nullable=True),
    sa.Column('durum', sa.VARCHAR(length=30), nullable=True),
    sa.Column('dosya_yolu', sa.VARCHAR(length=300), nullable=True),
    sa.Column('ai_ham_veri', sa.TEXT(), nullable=True),
    sa.Column('notlar', sa.TEXT(), nullable=True),
    sa.Column('yukleme_tarihi', sa.DATETIME(), nullable=True),
    sa.Column('yukleyen_id', sa.INTEGER(), nullable=True),
    sa.Column('talep_id', sa.INTEGER(), nullable=True),
    sa.Column('odeme_tarihi', sa.DATE(), nullable=True),
    sa.Column('ai_guvenskoru', sa.FLOAT(), nullable=True),
    sa.Column('fatura_kuru', sa.FLOAT(), nullable=True),
    sa.Column('odeme_kuru', sa.FLOAT(), nullable=True),
    sa.Column('tl_karsiligi', sa.FLOAT(), nullable=True),
    sa.Column('odenen_tl', sa.FLOAT(), nullable=True),
    sa.Column('fatura_turu', sa.VARCHAR(length=20), server_default=sa.text("'normal'"), nullable=True),
    sa.Column('ana_fatura_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ana_fatura_id'], ['fatura.id'], ),
    sa.ForeignKeyConstraint(['talep_id'], ['talep_formu.id'], ),
    sa.ForeignKeyConstraint(['tedarikci_id'], ['tedarikci.id'], ),
    sa.ForeignKeyConstraint(['yukleyen_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
