"""baslangic

Revision ID: dfd6d2c51497
Revises: 
Create Date: 2026-04-26 04:50:45.424897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd6d2c51497'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talep_formu', schema=None) as batch_op:
        batch_op.drop_column('kullanilan_alan')
        batch_op.drop_column('kullanim_amaci')
        batch_op.drop_column('proje_makine')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talep_formu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proje_makine', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('kullanim_amaci', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('kullanilan_alan', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
